spring:
  application:
    name: exam2
  datasource:
    url: jdbc:postgresql://localhost:5434/parkingdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_DHnNHfkCk/.well-known/jwks.json

server:
  port: 8081
